import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card } from "@/components/ui/card";
import { Copy, Download } from "lucide-react";
import ToolPage from "@/components/ToolPage";
import { FileText } from "lucide-react";
import { toast } from "sonner";

export default function RobotsGeneratorPage() {
  const [domain, setDomain] = useState("example.com");
  const [disallowPaths, setDisallowPaths] = useState("/admin\n/private\n/temp");
  const [crawlDelay, setCrawlDelay] = useState("1");
  const [userAgents, setUserAgents] = useState("*\nGooglebot\nBingbot");
  const [robotsContent, setRobotsContent] = useState("");

  const generateRobots = () => {
    let content = "# Robots.txt for " + domain + "\n";
    content += "# Generated by ToolVerse - Robots.txt Generator\n";
    content += "# Last updated: " + new Date().toISOString().split('T')[0] + "\n\n";

    const agents = userAgents.split("\n").filter((a) => a.trim());
    const disallows = disallowPaths.split("\n").filter((p) => p.trim());

    agents.forEach((agent) => {
      content += `User-agent: ${agent.trim()}\n`;
      content += `Allow: /\n`;
      disallows.forEach((path) => {
        content += `Disallow: ${path.trim()}\n`;
      });
      if (crawlDelay && agent.trim() !== "*") {
        content += `Crawl-delay: ${crawlDelay}\n`;
      }
      content += "\n";
    });

    content += `Sitemap: https://${domain}/sitemap.xml\n`;

    setRobotsContent(content);
    toast.success("Robots.txt generated successfully!");
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(robotsContent);
    toast.success("Copied to clipboard!");
  };

  const downloadFile = () => {
    const element = document.createElement("a");
    const file = new Blob([robotsContent], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = "robots.txt";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    toast.success("File downloaded!");
  };

  return (
    <ToolPage
      toolName="Robots.txt Generator"
      toolDescription="Generate optimized robots.txt files to control search engine crawling and indexing of your website."
      toolIcon={<FileText className="w-8 h-8" />}
      category="SEO Tools"
      keywords={["robots.txt", "SEO", "crawling", "indexing", "search engines"]}
      features={[
        "Generate custom robots.txt files",
        "Control crawler access by user-agent",
        "Set crawl delays",
        "Specify disallowed paths",
        "Add sitemap URLs",
        "Download or copy results",
      ]}
      faqs={[
        {
          question: "What is robots.txt?",
          answer:
            "Robots.txt is a file that tells search engines which pages they can and cannot crawl on your website. It's placed in the root directory of your site.",
        },
        {
          question: "How do I use this tool?",
          answer:
            "Enter your domain name, specify which paths should be disallowed, set crawl delays if needed, and click Generate. Then download or copy the content to your robots.txt file.",
        },
        {
          question: "What's the difference between Allow and Disallow?",
          answer:
            "Allow tells search engines they can crawl a path, while Disallow tells them not to. By default, all paths are allowed unless specified otherwise.",
        },
        {
          question: "Can I set different rules for different search engines?",
          answer:
            "Yes! You can specify different User-agents (like Googlebot, Bingbot) and set different rules for each. Use * for rules that apply to all bots.",
        },
        {
          question: "What's crawl-delay?",
          answer:
            "Crawl-delay specifies how many seconds a search engine should wait between requests. This helps prevent server overload from aggressive crawling.",
        },
      ]}
    >
      <div className="space-y-6">
        {/* Domain Input */}
        <div>
          <label className="block text-sm font-medium text-foreground mb-2">
            Your Domain
          </label>
          <Input
            placeholder="example.com"
            value={domain}
            onChange={(e) => setDomain(e.target.value)}
            className="w-full"
          />
          <p className="text-xs text-muted-foreground mt-1">
            Enter your domain without https:// or www
          </p>
        </div>

        {/* User Agents */}
        <div>
          <label className="block text-sm font-medium text-foreground mb-2">
            User Agents (one per line)
          </label>
          <Textarea
            placeholder="*&#10;Googlebot&#10;Bingbot"
            value={userAgents}
            onChange={(e) => setUserAgents(e.target.value)}
            className="w-full h-24"
          />
          <p className="text-xs text-muted-foreground mt-1">
            * applies to all bots. Specify individual bots for custom rules.
          </p>
        </div>

        {/* Disallow Paths */}
        <div>
          <label className="block text-sm font-medium text-foreground mb-2">
            Disallow Paths (one per line)
          </label>
          <Textarea
            placeholder="/admin&#10;/private&#10;/temp"
            value={disallowPaths}
            onChange={(e) => setDisallowPaths(e.target.value)}
            className="w-full h-24"
          />
          <p className="text-xs text-muted-foreground mt-1">
            Paths that search engines should not crawl
          </p>
        </div>

        {/* Crawl Delay */}
        <div>
          <label className="block text-sm font-medium text-foreground mb-2">
            Crawl Delay (seconds)
          </label>
          <Input
            type="number"
            placeholder="1"
            value={crawlDelay}
            onChange={(e) => setCrawlDelay(e.target.value)}
            className="w-full"
            min="0"
          />
          <p className="text-xs text-muted-foreground mt-1">
            Wait time between requests (0 for no delay)
          </p>
        </div>

        {/* Generate Button */}
        <Button onClick={generateRobots} className="w-full bg-primary hover:bg-primary/90">
          Generate Robots.txt
        </Button>

        {/* Output */}
        {robotsContent && (
          <Card className="p-4 bg-secondary/20 border-border">
            <div className="flex justify-between items-center mb-4">
              <h3 className="font-semibold text-foreground">Generated robots.txt</h3>
              <div className="flex gap-2">
                <Button
                  size="sm"
                  variant="outline"
                  onClick={copyToClipboard}
                  className="flex items-center gap-2"
                >
                  <Copy className="w-4 h-4" />
                  Copy
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={downloadFile}
                  className="flex items-center gap-2"
                >
                  <Download className="w-4 h-4" />
                  Download
                </Button>
              </div>
            </div>
            <pre className="bg-white p-4 rounded border border-border overflow-x-auto text-sm font-mono text-foreground/80">
              {robotsContent}
            </pre>
          </Card>
        )}
      </div>
    </ToolPage>
  );
}
